### ISSUE TITLE
Compile error

### ISSUE THREAD

**Issue by pendex900x** [vjgpt/Vehicle-Number-Plate-Reading#1]
In python 3 give this error:

```
py test.py

Traceback (most recent call last):
  File "test.py", line 24, in <module>
    (new, cnts, _) = cv2.findContours(edged.copy(), cv2.RETR_LIST, cv2.CHAIN_APPROX_SIMPLE)
ValueError: not enough values to unpack (expected 3, got 2)
```

And in python 2,7 this error:

```
py -2 test.py

Traceback (most recent call last):
  File "test.py", line 24, in <module>
    (new, cnts, _) = cv2.findContours(edged.copy(), cv2.RETR_LIST, cv2.CHAIN_APPROX_SIMPLE)
ValueError: need more than 2 values to unpack
```

What versions of dependencies do you use?? and which one py version?

**Comment by priyankakanse123** [comment]
I am too getting this error. Anyone can help with this?

**Comment by warpdriv** [comment]
It's a clean solution compared to the others...

Found this https://stackoverflow.com/questions/40278444/error-using-cv2-findcontours-with-python so depending on what version of your environment.

That said, I could not get past this error too...

**Comment by Laxman57854** [comment]
OpenCV version 3. cv2.findContours does return 3 objects in that version. but in openCV version 4 it return 2 objects only

**Comment by Rahesh31** [comment]
Remove new, in that it will work

**Comment by aliaazri** [comment]
Yes. Remove "new" in the parameter, then it will work..

**Comment by naveen12124139** [comment]
> Remove new, in that it will work

bro, u saved a lot of time
